# Generated by Django 4.0 on 2022-01-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField()),
                ('type', models.CharField(choices=[('SVR', 'Server'), ('STR', 'Storage'), ('SWT', 'Switch')], max_length=8)),
                ('site', models.CharField(choices=[('TOT', 'Totowa'), ('PSC', 'Piscataway')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnumber', models.IntegerField()),
                ('message_id', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=10)),
                ('severity', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('message', models.CharField(max_length=255)),
                ('raw_data', models.CharField(max_length=255)),
                ('FQDD', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logviewer.asset')),
            ],
        ),
    ]
