# Generated by Django 4.0 on 2022-01-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
