# Generated by Django 4.0 on 2022-01-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0002_rename_logs_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='FQDD',
            new_name='fqdd',
        ),
    ]
