# Generated by Django 4.0 on 2022-01-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0003_rename_fqdd_log_fqdd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='ip',
            new_name='IP',
        ),
        migrations.AddField(
            model_name='log',
            name='agent_id',
            field=models.CharField(choices=[('UEFI_SS_USC', 'UEFI_SS_USC'), ('CusOsUp', 'CusOsUp'), ('UEFI_Inventory', 'UEFI_Inv'), ('iDRAC', 'iDRAC'), ('UEFI_DCS', 'UEFI_DCS'), ('SEL', 'SEL'), ('RACLOG', 'RACLOG'), ('DE', 'DE'), ('WSMAN', 'WSMAN'), ('RACADM', 'RACADM'), ('iDRAC_GUI', 'iDRAC_GUI'), ('CMC', 'CMC')], default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('System', 'System'), ('Storage', 'Storage'), ('Worknotes', 'Worknotes'), ('Config', 'Config'), ('Updates', 'Updates'), ('Audit', 'Audit')], max_length=9),
        ),
        migrations.AlterField(
            model_name='log',
            name='seqnumber',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='severity',
            field=models.CharField(choices=[('Warning', 'Warning'), ('Critical', 'Critical'), ('Info', 'Info')], max_length=8),
        ),
    ]
