# Generated by Django 4.0 on 2022-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0004_rename_ip_asset_ip_log_agent_id_alter_log_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
