# Generated by Django 4.0 on 2022-01-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0005_log_resolved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AddField(
            model_name='asset',
            name='phase',
            field=models.SmallIntegerField(choices=[(1, 'Phase 1'), (2, 'Phase 2')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Warning', 'Warning'), ('Info', 'Info')], max_length=8),
        ),
    ]
