# Generated by Django 4.0 on 2022-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0007_alter_log_agent_id_alter_log_category_alter_log_fqdd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='seqnumber',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
