# Generated by Django 4.0 on 2022-01-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0008_alter_log_seqnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='seqnumber',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
