# Generated by Django 4.0 on 2022-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0009_alter_log_seqnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='agent_id',
            field=models.CharField(blank=True, choices=[('UEFI_SS_USC', 'UEFI_SS_USC'), ('CusOsUp', 'CusOsUp'), ('UEFI_Inventory', 'UEFI_Inv'), ('iDRAC', 'iDRAC'), ('UEFI_DCS', 'UEFI_DCS'), ('SEL', 'SEL'), ('RACLOG', 'RACLOG'), ('DE', 'DE'), ('WSMAN', 'WSMAN'), ('RACADM', 'RACADM'), ('iDRAC_GUI', 'iDRAC_GUI'), ('CMC', 'CMC')], max_length=14),
        ),
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(blank=True, choices=[('System', 'System'), ('Storage', 'Storage'), ('Worknotes', 'Worknotes'), ('Config', 'Config'), ('Updates', 'Updates'), ('Audit', 'Audit')], max_length=9),
        ),
        migrations.AlterField(
            model_name='log',
            name='fqdd',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='message_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='log',
            name='raw_data',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='seqnumber',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='severity',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Warning', 'Warning'), ('Info', 'Info')], max_length=8),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
