# Generated by Django 4.0 on 2022-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0010_alter_log_agent_id_alter_log_category_alter_log_fqdd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='password',
            field=models.CharField(default='viewer', max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='username',
            field=models.CharField(default='viewer', max_length=20),
        ),
    ]
