# Generated by Django 4.0 on 2022-01-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0011_asset_password_asset_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='log',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='log',
            name='odata_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
