# Generated by Django 4.0 on 2022-01-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0012_rename_timestamp_log_created_log_name_log_odata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
