# Generated by Django 4.0 on 2022-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0013_alter_log_message_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'get_latest_by': 'created'},
        ),
        migrations.AddField(
            model_name='asset',
            name='port',
            field=models.SmallIntegerField(blank=True, default=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='password',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='asset',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
