# Generated by Django 4.0 on 2022-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0014_alter_log_options_asset_port_alter_asset_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='port',
            field=models.SmallIntegerField(null=True),
        ),
    ]
