# Generated by Django 4.0 on 2022-01-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0015_alter_asset_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('SVR', 'Server'), ('STR', 'Storage'), ('SWT', 'Switch'), ('TST', 'Test')], max_length=8),
        ),
    ]
