# Generated by Django 4.0 on 2022-02-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0017_alter_log_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='severity',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Warning', 'Warning'), ('OK', 'OK')], max_length=8),
        ),
    ]
